export interface ICategory {
  id: number,
  orderBy: number,
  name: string,
  nameTranslated: object,
  url: string,
  autogeneratedSlug: string,
  customSlug: string,
  productCount: number,
  description: string,
  descriptionTranslated: object,
  enabled: true,
  isSampleCategory: false,
  seoTitle: string,
  seoDescription: string,
  alt: object
}
