export interface ICategoriesApi {
  count: number;
  items: ICategory[];
  limit: number;
  offset: number;
  total: number;
}

export interface ICategory {
  id: number;
  orderBy: number;
  name: string;
  nameTranslated: object;
  url: string;
  autogeneratedSlug: string;
  customSlug: string;
  productCount: number;
  description: string;
  descriptionTranslated: object;
  enabled: boolean;
  isSampleCategory: boolean;
  seoTitle: string;
  seoDescription: string;
  alt: object;
}
