export interface IProduct {
  id: number;
  sku: string;
  thumbnailUrl: string;
  unlimited: boolean;
  inStock: boolean;
  name: string;
  price: number;
  priceInProductList: number;
  defaultDisplayedPrice: number;
  defaultDisplayedPriceFormatted: string;
  tax: object;
  lowestPrice: number;
  defaultDisplayedLowestPrice: number;
  defaultDisplayedLowestPriceFormatted: string;
  lowestPriceSettings: object;
  isShippingRequired: boolean;
  hasFreeShipping: boolean;
  weight: number;
  url: string;
  autogeneratedSlug: string;
  customSlug: string;
  created: string;
  updated: string;
  createTimestamp: number;
  updateTimestamp: number;
  productClassId: number;
  enabled: boolean;
  options: object[];
  fixedShippingRateOnly: boolean;
  fixedShippingRate: number;
  shipping: object;
  defaultCombinationId: number;
  imageUrl: string;
  smallThumbnailUrl: string;
  hdThumbnailUrl: string;
  originalImageUrl: string;
  originalImage: object;
  borderInfo: object;
  description: string;
  galleryImages: IGalleryImages[];
  media: object;
  categoryIds: number[];
  categories: ICategories[];
  defaultCategoryId: number;
  seoTitle: string;
  seoDescription: string;
  attributes: object[];
  relatedProducts: object;
  combinations: object[];
  volume: number;
  showOnFrontpage: number;
  isSampleProduct: boolean;
  googleItemCondition: string;
  isGiftCard: symbol;
  discountsAllowed: boolean;
  nameYourPriceEnabled: symbol;
  quantity: number;
}

interface IGalleryImages {
  id: number;
  url: string;
  thumbnail: string;
  originalImageUrl: string;
  imageUrl: string;
  hdThumbnailUrl: string;
  thumbnailUrl: string;
  smallThumbnailUrl: string;
  width: number;
  height: number;
  orderBy: number;
  borderInfo: object;
}

export interface IProductsApi {
  count: number;
  items: IProduct[];
  length: number;
  limit: number;
  offset: number;
  total: number;
}

export interface ICategories {
  enabled: boolean;
  id: number;
  name: string;
  nameTranslated: string;
}
